### ISSUE TITLE
API inconsistency

### ISSUE THREAD

**Issue by bryancostanich** [MelbourneDeveloper/Device.Net#105]
The call `GetDevicesAsync` requires a `List<FilterDeviceDefinition>` in order to make it work, but if you want to get all the devices, it looks like you have to use the `GetConnectedDeviceDefinitionsAsync` method, which, confusingly, also requires the same parameter, but allows a `null` to be passed. The weird thing about this, is that they seemingly do the same thing, but the first returns a `List<IDevice>` and the second returns `IEnumerable<ConnectedDeviceDefinition>`.

Why not just allow `GetDevicesAsync` to take a `null` for all devices? 

Why does GetConnectedDeviceDefinitionsAsync return a different type? I see that `IDevice` contains a `ConnectedDeviceDefinition` anyway?

**Comment by MelbourneDeveloper** [comment]
@bryancostanich 

`GetConnectedDeviceDefinitionsAsync` and `GetDevicesAsync` do two different things. 

`GetConnectedDeviceDefinitionsAsync` gets a list of device definitions - not device connections. It lists what is connected, but doesn't attempt to connect to them. This is part of the core framework in that it belongs to `IDeviceFactory`. I believe that the design of this method and interface is good.

`GetDevicesAsync` tries to actually connect to the devices. In most cases you wouldn't want to connect to multiple devices. You will probably only want to connect to one device, and that's how this class is designed. But, more importantly, `GetDevicesAsync` is not part of the core framework interfaces. It's a layer on top that handles enumeration and connection/disconnection. I'm not sure if this method is designed well or not, but the whole `DeviceManager` class needs to some refactoring. I agree it is confusing. I have put a TODO in for refactoring this in [Version 4](https://github.com/MelbourneDeveloper/Device.Net/issues/107). 

> Why not just allow GetDevicesAsync to take a null for all devices?

Is there a real life use case where you'd want to connect to all devices at the same time?

> Why does GetConnectedDeviceDefinitionsAsync return a different type?

See the first point.

**Comment by bryancostanich** [comment]
I don't necessarily need to connect, I just need to enumerate all devices. I'm guess that's likely a pretty common use case. Especially given that's the what one of the main samples does in LibUsb. In that case, it sounds like I need `GetConnectedDeviceDefinitionsAsync`. I suggest adding an overload that doesn't require a filter.

I was confused by the `GetDevicesAsync` because there's no "connect" verb in the name, or any indication that it does anything other than get the devices. So it wasn't readily apparent that I was connecting. I'm not sure I even understand the use case in which you would filter and connect all at once, but it sounds like you're using it with your crypto stuff. In that case, I suggest a method rename. Just my 2¢. :)

**Comment by MelbourneDeveloper** [comment]
> I just need to enumerate all devices.

That's simple. You don't need `GetDevicesAsync`. [This article](https://github.com/MelbourneDeveloper/Device.Net/wiki/Enumerating-Connected-Devices) explains how to do it with `GetConnectedDeviceDefinitionsAsync`

> I was confused by the GetDevicesAsync because there's no "connect" verb in the name

Fair call.

> I'm not sure I even understand the use case in which you would filter and connect all at once, but it sounds like you're using it with your crypto stuff.

There is no use case as far as I know. No. I don't do that with any crypto stuff. I was answering your question:

> Why not just allow GetDevicesAsync to take a null for all devices?

So, I think we can say that it doesn't make sense to have a method that accepts no filters that would connect to all devices at once.

@bryancostanich

**Comment by MelbourneDeveloper** [comment]
@bryancostanich 

> I suggest a method rename

Fair call. Please make your suggestion for a new name [here](https://github.com/MelbourneDeveloper/Device.Net/issues/107). I've already created a stub for it. Just bear in mind that what it is doing is actually initializing the device. So, a less misleading name would probably include "Initialize"

**Comment by AalapMistry** [comment]
Status Bit:1
07FFFFFFFFFFFFFF
Line No:2
High:0
Low:16
Status Bit:1
070011D9FC800100
Line No:3
High:0
Low:24
Status Bit:1
07011213D7FFFFFF
Line No:4
High:0
Low:32
Status Bit:1
07029A0100001100
Line No:5
High:0
Low:40
Status Bit:1
0703000000000000
Line No:6
High:0
Low:48
Status Bit:1
0704C22200000000
Line No:7
High:0
Low:56
Status Bit:1
0705640000000C00
Line No:8
High:0
Low:64
Status Bit:1
0706000000000000
Line No:9
High:0
Low:72
Status Bit:1
0707112000000000
Line No:10
High:0
Low:80
Status Bit:1
0708960000001600
Line No:11
High:0
Low:88
Status Bit:1
0709000000000000
Line No:12
High:0
Low:96
Status Bit:1
070A121A00000000
Line No:13
High:0
Low:104
Status Bit:1
070B640000000C00
Line No:14
High:0
Low:112
Status Bit:1
070C000000000000
Line No:15
High:0
Low:120
Status Bit:1
070D121900000000
Line No:16
High:0
Low:128
Status Bit:1
070E7D0000001200
Line No:17
High:0
Low:136
Status Bit:1
070F000000000000
Line No:18
High:0
Low:144
Status Bit:1
0710120900000000
Line No:19
High:0
Low:152
Status Bit:1
0711000000001400
Line No:20
High:0
Low:160
Status Bit:1
0712000000000000
Line No:21
High:0
Low:168
Status Bit:1
07131313D7FFFFFF
Line No:22
High:0
Low:176
Status Bit:1
07149A0100001103
Line No:23
High:0
Low:184
Status Bit:1
071508AA0AAA0000
Line No:24
High:0
Low:192
Status Bit:1
0716C32200000000
Line No:25
High:0
Low:200
Status Bit:1
0717640000000C03
Line No:26
High:0
Low:208
Status Bit:1
071808AA0AAA0000
Line No:27
High:0
Low:216
Status Bit:1
0719112000000000
Line No:28
High:0
Low:224
Status Bit:1
071A960000001600
Line No:29
High:0
Low:232
Status Bit:1
071B0850A9FA0000
Line No:30
High:0
Low:240
Status Bit:1
071C101A00000000
Line No:31
High:0
Low:248
Status Bit:1
071D640000000C03
Line No:32
High:1
Low:0
Status Bit:1
071E08A0AAAA0000
Line No:33
High:1
Low:8
Status Bit:1
071F131900000000
Line No:34
High:1
Low:16
Status Bit:1
07207D0000001203
Line No:35
High:1
Low:24
Status Bit:1
072108A00AAA0000
Line No:36
High:1
Low:32
Status Bit:1
0722120900000000
Line No:37
High:1
Low:40
Status Bit:1
0723000000001400
Line No:38
High:1
Low:48
Status Bit:1
0724000000000000
Line No:39
High:1
Low:56
Status Bit:1
07254213D7FFFFFF
Line No:40
High:1
Low:64
Status Bit:1
07269A0100001100
Line No:41
High:1
Low:72
Status Bit:1
0727000000000000
Line No:42
High:1
Low:80
Status Bit:1
0728C22200000000
Line No:43
High:1
Low:88
Status Bit:1
0729640000000C00
Line No:44
High:1
Low:96
Status Bit:1
072A000000000000
Line No:45
High:1
Low:104
Status Bit:1
072B112000000000
Line No:46
High:1
Low:112
Status Bit:1
072C960000001600
Line No:47
High:1
Low:120
Status Bit:1
072D000000000000
Line No:48
High:1
Low:128
Status Bit:1
072E121A00000000
Line No:49
High:1
Low:136
Status Bit:1
072F640000000C00
Line No:50
High:1
Low:144
Status Bit:1
0730000000000000
Line No:51
High:1
Low:152
Status Bit:1
0731121900000000
Line No:52
High:1
Low:160
Status Bit:1
07327D0000001200
Line No:53
High:1
Low:168
Status Bit:1
0733000000000000
Line No:54
High:1
Low:176
Status Bit:1
0734120900000000
Line No:55
High:1
Low:184
Status Bit:1
0735000000001400
Line No:56
High:1
Low:192
Status Bit:1
0736000000000000
Line No:57
High:1
Low:200
Status Bit:1
0737112200000000
Line No:58
High:1
Low:208
Status Bit:1
0738640000000C00
Line No:59
High:1
Low:216
Status Bit:1
0739000000000000
Line No:60
High:1
Low:224
Status Bit:1
073AC12000000000
Line No:61
High:1
Low:232
Status Bit:1
073B960000001600
Line No:62
High:1
Low:240
Status Bit:1
073C000000000000
Line No:63
High:1
Low:248
Status Bit:1
073D111A00000000
Line No:64
High:2
Low:0
Status Bit:1
073E640000000C00
Line No:65
High:2
Low:8
Status Bit:1
073F000000000000
Line No:66
High:2
Low:16
Status Bit:1
0740101A00000000
Line No:67
High:2
Low:24
Status Bit:1
0741640000000C00
Line No:68
High:2
Low:32
Status Bit:1
0742000000000000
Line No:69
High:2
Low:40
Status Bit:1
0743101A00000000
Line No:70
High:2
Low:48
Status Bit:1
0744640000000C00
Line No:71
High:2
Low:56
Status Bit:1
0745000000000000
Line No:72
High:2
Low:64
Status Bit:1
0746120900000000
Line No:73
High:2
Low:72
Status Bit:1
0747000000001400
Line No:74
High:2
Low:80
Status Bit:1
0748000000000000
Line No:75
High:2
Low:88
Status Bit:1
0749112000000000
Line No:76
High:2
Low:96
Status Bit:1
074A960000001600
Line No:77
High:2
Low:104
Status Bit:1
074B000000000000
Line No:78
High:2
Low:112
Status Bit:1
074CC12000000000
Line No:79
High:2
Low:120
Status Bit:1
074D960000001600
Line No:80
High:2
Low:128
Status Bit:1
074E000000000000
Line No:81
High:2
Low:136
Status Bit:1
074F102000000000
Line No:82
High:2
Low:144
Status Bit:1
0750960000001600
Line No:83
High:2
Low:152
Status Bit:1
0751000000000000
Line No:84
High:2
Low:160
Status Bit:1
0752102000000000
Line No:85
High:2
Low:168
Status Bit:1
0753960000001600
Line No:86
High:2
Low:176
Status Bit:1
0754000000000000
Line No:87
High:2
Low:184
Status Bit:1
0755102000000000
Line No:88
High:2
Low:192
Status Bit:1
0756960000001600
Line No:89
High:2
Low:200
Status Bit:1
0757000000000000
Line No:90
High:2
Low:208
Status Bit:1
0758000900000000
Line No:91
High:2
Low:216
Status Bit:1
0759000000001400
Line No:92
High:2
Low:224
Status Bit:1
075A000000000000
Line No:93
High:2
Low:232
Status Bit:1
075E093400000000
Line No:94
High:2
Low:240
Status Bit:1
075F010000000000
Line No:95
High:2
Low:248
Status Bit:1
0760000000000000
Line No:96
High:3
Low:0
Status Bit:1
0761093500000000
Line No:97
High:3
Low:8
Status Bit:1
0762060000000000
Line No:98
High:3
Low:16
Status Bit:1
0763000000000000
Line No:99
High:3
Low:24
Status Bit:1
0764093600000000
Line No:100
High:3
Low:32
Status Bit:1
0765010000000000
Line No:101
High:3
Low:40
Status Bit:1
0766000000000000
Line No:102
High:3
Low:48
Status Bit:1
0767093700000000
Line No:103
High:3
Low:56
Status Bit:1
0768010000000000
Line No:104
High:3
Low:64
Status Bit:1
0769000000000000
Line No:105
High:3
Low:72
Status Bit:1
076A093800000000
Line No:106
High:3
Low:80
Status Bit:1
076B010000000000
Line No:107
High:3
Low:88
Status Bit:1
076C000000000000
Line No:108
High:3
Low:96
Status Bit:1
076D093900000000
Line No:109
High:3
Low:104
Status Bit:1
076E010000000000
Line No:110
High:3
Low:112
Status Bit:1
076F000000000000
Line No:111
High:3
Low:120
Status Bit:1
0770093C00000000
Line No:112
High:3
Low:128
Status Bit:1
0771010000000000
Line No:113
High:3
Low:136
Status Bit:1
0772000000000000
Line No:114
High:3
Low:144
Status Bit:1
0773093A00000000
Line No:115
High:3
Low:152
Status Bit:1
0774010000000000
Line No:116
High:3
Low:160
Status Bit:1
0775000000000000
Line No:117
High:3
Low:168
Status Bit:1
0776093B00000000
Line No:118
High:3
Low:176
Status Bit:1
0777010000000000
Line No:119
High:3
Low:184
Status Bit:1
0778000000000000
Line No:120
High:3
Low:192
Status Bit:1
0779093D00000000
Line No:121
High:3
Low:200
Status Bit:1
077A010000000000
Line No:122
High:3
Low:208
Status Bit:1
077B000000000000
Line No:123
High:3
Low:216
Status Bit:1
077C093E00000000
Line No:124
High:3
Low:224
Status Bit:1
077D010000000000
Line No:125
High:3
Low:232
Status Bit:1
077E000000000000
Line No:126
High:3
Low:240
Status Bit:1
077F094200000000
Line No:127
High:3
Low:248
Status Bit:1
0780010000000000
Line No:128
High:4
Low:0
Status Bit:1
0781000000000000
Line No:129
High:4
Low:8
Status Bit:1
0782094300000000
Line No:130
High:4
Low:16
Status Bit:1
0783010000000000
Line No:131
High:4
Low:24
Status Bit:1
0784000000000000
Line No:132
High:4
Low:32
Status Bit:1
0785093F00000000
Line No:133
High:4
Low:40
Status Bit:1
0786010000000000
Line No:134
High:4
Low:48
Status Bit:1
0787000000000000
Line No:135
High:4
Low:56
Status Bit:1
0788094000000000
Line No:136
High:4
Low:64
Status Bit:1
0789010000000000
Line No:137
High:4
Low:72
Status Bit:1
078A000000000000
Line No:138
High:4
Low:80
Status Bit:1
078B0B2F00000000
Line No:139
High:4
Low:88
Status Bit:1
078C640000000000
Line No:140
High:4
Low:96
Status Bit:1
078D000000000000
Line No:141
High:4
Low:104
Status Bit:1
078E093500000000
Line No:142
High:4
Low:112
Status Bit:1
078F050000000000
Line No:143
High:4
Low:120
Status Bit:1
0790000000000000
Line No:144
High:4
Low:128
Status Bit:1
0791093500000000
Line No:145
High:4
Low:136
Status Bit:1
0792040000000000
Line No:146
High:4
Low:144
Status Bit:1
0793000000000000
Line No:147
High:4
Low:152
Status Bit:1
0797F02900000000
Line No:148
High:4
Low:160
Status Bit:1
0798000000000000
Line No:149
High:4
Low:168
Status Bit:1
0799000000000000
Line No:150
High:4
Low:176
Status Bit:1
079A00000000401F
Line No:151
High:4
Low:184
Status Bit:1
079B803EC05D007D
Line No:152
High:4
Low:192
Status Bit:1
079CFFFFFFFFFFFF
Line No:153
High:4
Low:200
Status Bit:1
079DFFFFFFFFFFFF
Line No:154
High:4
Low:208
Status Bit:1
079E00000000401F
Line No:155
High:4
Low:216
Status Bit:1
079F803EC05D007D
Line No:156
High:4
Low:224
Status Bit:1
07A0FFFFFFFFFFFF
Line No:157
High:4
Low:232
Status Bit:1
07A1FFFFFFFFFFFF
Line No:158
High:4
Low:240
Status Bit:1
07A200000000401F
Line No:159
High:4
Low:248
Status Bit:1
07A3803EC05D007D
Line No:160
High:5
Low:0
Status Bit:1
07A4FFFFFFFFFFFF
Line No:161
High:5
Low:8
Status Bit:1
07A5FFFFFFFFFFFF
Line No:162
High:5
Low:16
Status Bit:1
07A600000000401F
Line No:163
High:5
Low:24
Status Bit:1
07A7803EC05D007D
Line No:164
High:5
Low:32
Status Bit:1
07A8FFFFFFFFFFFF
Line No:165
High:5
Low:40
Status Bit:1
07A9FFFFFFFFFFFF
Line No:166
High:5
Low:48
Status Bit:1
07AA00000000401F
Line No:167
High:5
Low:56
Status Bit:1
07AB803EC05D007D
Line No:168
High:5
Low:64
Status Bit:1
07ACFFFFFFFFFFFF
Line No:169
High:5
Low:72
Status Bit:1
07ADFFFFFFFFFFFF
Line No:170
High:5
Low:80
Status Bit:1
07AE00000000401F
Line No:171
High:5
Low:88
Status Bit:1
07AF803EC05D007D
Line No:172
High:5
Low:96
Status Bit:1
07B0FFFFFFFFFFFF
Line No:173
High:5
Low:104
Exception thrown: 'System.IO.IOException' in mscorlib.dll

Reading small frame lines from device it work but reading more frame lines it throw exception or device disconnected .

Help  i am reading data from above address High Low and random throw exeption while reading if more data frame line , else works fine if small lines frame data. 
Help or suggest me what to do ?

**Comment by st-arnold** [comment]
I was confused because of this as well. Good to hear there is improvement.

I found another API inconsistency in WinUsbApiCalls.cs:
Some P/Invoke signatures have IntPtr type for InterfaceHandle parameter while others have SafeFileHandle.

**Comment by MelbourneDeveloper** [comment]
@AalapMistry  could you please tell me what that log is from? I don't really understand...

@st-arnold , yes there are some APIs that are not designed perfectly. I'm very much open to code-design suggestions if you've got some ideas. If you want to test, you could try changing everything to SafeFileHandle.

**Comment by AalapMistry** [comment]
Please close that ticket , the issue is from firmware side ,Thanks for
replay

**Comment by MelbourneDeveloper** [comment]
Hi @bryancostanich 

Just letting you know that this issue is being closed because the API has been completely redesigned. V4 will be out soon.
