### ISSUE TITLE
how to monitor usb Pull out plug?

### ISSUE THREAD

**Issue by heartacker** [MelbourneDeveloper/Device.Net#116]
hi very nice to use this project, and i just do not know how to monitor my usb device pull or plug that {DevicesType = HID} in my windows 10;
THx A lot :D

**Comment by MelbourneDeveloper** [comment]
@heartacker , there is documentation for using the Device Listener here:

https://github.com/MelbourneDeveloper/Device.Net/wiki/Device-Listener

You can see examples in the events:

DevicePoller_DeviceInitialized
DevicePoller_DeviceDisconnected
