### ISSUE TITLE
Baud rates above 256000

### ISSUE THREAD

**Issue by seasniffer** [MelbourneDeveloper/Device.Net#124]
Any reason baud rates above 256000 are not allowed for the serial port class?

**Comment by MelbourneDeveloper** [comment]
@seasniffer 

Good question. I believe it's a windows level enum. Perhaps I haven't included all the options. If you do the research you might find it's easy to fix and do a pr for.

**Comment by MelbourneDeveloper** [comment]
@seasniffer actually, it is not an enum. Good question. Why don't you try removing the validation, and if it works, let me know the highest baud rate you can use.

**Comment by MelbourneDeveloper** [comment]
@seasniffer did you ever get around to trying this?

**Comment by MelbourneDeveloper** [comment]
Closing due to inactivty
