### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by sbogutzky** [MelbourneDeveloper/Device.Net#135]
I use macOS 10.15.5 and Visual Studio for Mac Community 8.6.8 (build 2). I installed libusb-1.0.23. 

"libusb-1.0 library not found.  This is often an indication that libusb-1.0 was installed to '/usr/local/lib' and mono.net is not looking for it there. To resolve this, add the path '/usr/local/lib' to '/etc/ld.so.conf' and run 'ldconfig' as root. (http://www.mono-project.com/DllNotFoundException)"

How can I fix this problem on my Mac?

**Comment by MelbourneDeveloper** [comment]
It usually just means that you need to install LibUsb. 

You can do it with homebrew

**Comment by sbogutzky** [comment]
I installed libusb via homebrew. 

/usr/local/Cellar/libusb/1.0.23: 26 files, 474.2KB

How can I add the path of libusb to the mono search path on my Mac.

**Comment by MelbourneDeveloper** [comment]
@sbogutzky OK. So, I'd recommend running the LibUsb sample in the MacOS samples. I tried it out from the master branch on a clean mac. This is the error I get. It's look like the same error as yours.

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/16697547/88852130-2c7f6b80-d231-11ea-896c-bbd5703b5bdb.png">

The error points to this resource:
https://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

I installed 1.0.23 with homebrew, and then I still get the error. 

When I look in the folder that it mentions, I see this:
<img width="165" alt="image" src="https://user-images.githubusercontent.com/16697547/88852856-35bd0800-d232-11ea-99d1-3b7150731825.png">

The etc folder is missing ld.so.conf
<img width="170" alt="image" src="https://user-images.githubusercontent.com/16697547/88853097-92202780-d232-11ea-8d8c-8d007ff596fa.png">

I'm thinking that perhaps an update to macOS has disturbed something. I tried using the terminal tool that the documentation suggests called ldconfig but I couldn't find that tool.

I suggest reading through mono resource mentioned above. I also suggest getting the latest version of LibUsbDotNet and trying out their latest samples. If their sample works, I will pull the latest from there in to Device.Net and get it working.

**Comment by sbogutzky** [comment]
The mono resource above only describe how to fix it on a linux system. Ldconfig is not available on macOS. The installation of libusb is not the problem. But how can we configure mono on macOS to search in the path /usr/local/bin for libusb?

**Comment by MelbourneDeveloper** [comment]
@sbogutzky I don't know. I would ask on the LibUsbDotNet GitHub page. Please let me know if you get it working.

**Comment by MelbourneDeveloper** [comment]
@sbogutzky Hi. I'm closing this issue because I believe that it is LibUsbDotNet related.

Still, if you have fixed this issue, a PR would be welcome.
