### ISSUE TITLE
Can't find Windows Sample

### ISSUE THREAD

**Issue by shrddr** [MelbourneDeveloper/Device.Net#149]
**Describe the issue**
Where do I find this Windows Sample if I installed the library via Nuget?

**Screenshots**
![image](https://user-images.githubusercontent.com/899919/93335602-63383200-f82f-11ea-9644-b6d45c5a3af8.png)

**Info**
 - Platform: Windows
 - Device Type: USB
 - Version: 3.1

**Comment by MelbourneDeveloper** [comment]
@shrddr you need to clone this repo. The sample is here: https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Usb.Net.WindowsSample
