### ISSUE TITLE
Example Code not compiling

### ISSUE THREAD

**Issue by shrddr** [MelbourneDeveloper/Device.Net#150]
**Describe the issue**
Example Code from README.md not compiling

**Your Code**
```
using Device.Net;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            WindowsUsbDeviceFactory.Register();
        }
    }
}
```

**Log / Stack Trace**
CS0103	The name 'WindowsUsbDeviceFactory' does not exist in the current context

**Info**
 - Platform: Windows
 - Device Type: USB
 - Version: 3.1

**Comment by MelbourneDeveloper** [comment]
Hi. You're best to download the samples and modify an existing one. 

But, you need to add the usb.net nuget package and import the Usb.Net.Windows namespace
