### ISSUE TITLE
SerialPort ReadAsync does not have a timeout option

### ISSUE THREAD

**Issue by jchavez1997** [MelbourneDeveloper/Device.Net#156]
SerialPort ReadAsync does not have a timeout option. When calling readasync, we do not seem to have the ability to stop reading on that serial port. This blocks until some data is read. It would be great to have a timeout option!

**Comment by MelbourneDeveloper** [comment]
@jchavez1997 the next version will have a cancellation token. Will this solve your issue?

**Comment by MelbourneDeveloper** [comment]
@jchavez1997 the operation now has a cancellation token. Closing this issue.
