### ISSUE TITLE
Bad Devices Information

### ISSUE THREAD

**Issue by Mxater** [MelbourneDeveloper/Device.Net#178]
**Describe the issue**
The devices get from GetConnectedDeviceDefenitionsAsync are combined.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/4630666/99802855-31856500-2b17-11eb-9ec9-ab89985d9566.png)

**Info**
 - Platform: Window C# framework.net 4.7.2 Window Forms Application
 - Version: [e.g. 3.31]

**Comment by MelbourneDeveloper** [comment]
@Mxater sorry I don't understand the issue.

**Comment by MelbourneDeveloper** [comment]
@Mxater  I am closing this issue because I do not understand what the issue is. If you provide more information, I will reopen the issue.
