### ISSUE TITLE
"Device.Net - Windows Samples.sln" does not include SerialPort.Net project

### ISSUE THREAD

**Issue by LiorBanaiKama** [MelbourneDeveloper/Device.Net#181]
so fresh build fails since the SerialPort.Net is not compiled

**Comment by MelbourneDeveloper** [comment]
@LiorBanaiKama it builds for me. Are you talking about develop branch?

Please post the error

**Comment by LiorBanai** [comment]
when I download the code (from master) and open the sln I get the following project in solution
![image](https://user-images.githubusercontent.com/36262995/100723572-98820400-33ca-11eb-89be-3303aa18e558.png)

so then I'm unable to compile:
![image](https://user-images.githubusercontent.com/36262995/100723771-dc750900-33ca-11eb-8bee-679c446c479d.png)


If I add the missing project. for example to the device folder it does compile and run:
![image](https://user-images.githubusercontent.com/36262995/100723892-f7e01400-33ca-11eb-8742-d2fc4e24209a.png)

**Comment by MelbourneDeveloper** [comment]
@LiorBanai yep. I there are too many solutions. I think you're looking at a broken one. I only tend to work on the all solution. 

Make sure you using the develop branch

**Comment by LiorBanai** [comment]
ok, thanks

**Comment by LiorBanai** [comment]
I suggest making develop the default branch since people unaware that it is more updated and github landing page points to master so downloading code will fetch old code:

![image](https://user-images.githubusercontent.com/36262995/100729567-996a6400-33d1-11eb-9f43-a3275eb63fbb.png)

**Comment by MelbourneDeveloper** [comment]
@LiorBanai that's how most repos work. The master or main branch represents the released code (Nuget package) and the develop branch represents what will be released next. 

You can read about it here
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by MelbourneDeveloper** [comment]
@LiorBanai closing this issue. The develop branch will become the master branch when the full version is released.
