### ISSUE TITLE
Device.Net.LibUsb 4.0 is not on nuget

### ISSUE THREAD

**Issue by schmitch** [MelbourneDeveloper/Device.Net#192]
currently https://www.nuget.org/packages/Device.Net.LibUsb/ is missing the version tag 4.0.0 on nuget, thus it is not possible to use it with recent samples.

**Comment by MelbourneDeveloper** [comment]
Yep. You have to use the alpha version. Turn on prerelease in the Nuget package manager. 

Testing is not complete on this Nuget. 

If it works for you, please let me know.
