### ISSUE TITLE
No public docs for 3.1

### ISSUE THREAD

**Issue by BryanCrotaz** [MelbourneDeveloper/Device.Net#209]
v 4.0 is listed as alpha, and it is recommended to use 3.1. But all the docs are for 4.0 - where are the 3.1 docs?

**Comment by MelbourneDeveloper** [comment]
Use version 4.0. It is not alpha.

https://www.nuget.org/packages/Device.Net/4.0.0

**Comment by BryanCrotaz** [comment]
Looks like it is alpha. NuGet docs say
"Alpha version. Please use 3.x for a stable release"

**Comment by MelbourneDeveloper** [comment]
4.0 is the release version

**Comment by MelbourneDeveloper** [comment]
@BryanCrotaz the text on the Nuget package is incorrect. I will try to fix that on the next release.
