### ISSUE TITLE
Docs don't specify how to set up factory in Linux

### ISSUE THREAD

**Issue by BryanCrotaz** [MelbourneDeveloper/Device.Net#211]
https://melbournedeveloper.github.io/Device.Net/articles/EnumeratingConnectedDevices.html

Only gives example for Windows. As the **CreateWindowsHidDeviceFactory** has the word Windows in it I assume there is an equivalent for Linux, but code completion doesn't discover it.

**Comment by MelbourneDeveloper** [comment]
@BryanCrotaz this is the [extension method](https://github.com/MelbourneDeveloper/Device.Net/blob/c0ab331b78b156cf3af91722661c35dae993e31e/src/Device.Net.LibUsb/LibUsbFactoryExtensions.cs#L15) for creating LibUsb device factories. This should work on any platform, but the version of LibUsbDotNet has not been tested on all platforms.

**Comment by BryanCrotaz** [comment]
Can you add this to the documented example?

**Comment by BryanCrotaz** [comment]
Do  I also need to call `LibUsbUsbDeviceFactory.Register();` ?

**Comment by MelbourneDeveloper** [comment]
> Do I also need to call LibUsbUsbDeviceFactory.Register();

No
