### ISSUE TITLE
Device.Net.LibUsb not compatible with 4.0.0

### ISSUE THREAD

**Issue by BryanCrotaz** [MelbourneDeveloper/Device.Net#212]
```
LibUsbUsbDeviceFactory.Register();
```

Error: _You must add a reference to assembly Device.Net 3.1.0.0_

How do we make this work with Device.Net 4.0?

**Comment by MelbourneDeveloper** [comment]
Please see https://github.com/MelbourneDeveloper/Device.Net/issues/211
