### ISSUE TITLE
Device.Net.LibUsb 2.6 missing on NuGet

### ISSUE THREAD

**Issue by schmitch** [MelbourneDeveloper/Device.Net#52]
Hello. currently https://www.nuget.org/packages/Device.Net.LibUsb/ misses the 2.6 version, thus it will fail with runtime exceptions, if the version 2.6 of device.net is installed.

The error is always:

```
TypeLoadException: Method 'Close' in type 'Device.Net.LibUsb.LibUsbDevice' from assembly 'Device.Net.LibUsb, Version=2.5.1.0, Culture=neutral, PublicKeyToken=918542c6e3a3318a' does not have an implementation.
```

**Comment by MelbourneDeveloper** [comment]
@schmitch

Thanks for letting me know! I will try to fix it as soon as possible.

**Comment by MelbourneDeveloper** [comment]
@schmitch . It's fixed. Please let me know if this fixed the problem!

https://www.nuget.org/packages/Device.Net.LibUsb/2.6.1

**Comment by schmitch** [comment]
Thanks, it looks working now!
