### ISSUE TITLE
How to enumerate all connected HID devices?

### ISSUE THREAD

**Issue by pc8181** [MelbourneDeveloper/Device.Net#60]
m newbie here ...
Can i get all connected HID devices with it's VID and PID ?

can i get sample codes ?.

Thanks...

**Comment by pc8181** [comment]
`
          Imports Device.Net
           Imports Hid.Net.Windows

    Public Class Form1
       Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            GetHID()
        Catch ex As Exception
        End Try
    End Sub

    Public Async Sub GetHID()
        WindowsHidDeviceFactory.Register()
        Dim dfnt As New FilterDeviceDefinition With {.DeviceType = DeviceType.Hid, .VendorId = &H5, .ProductId = &H5}
        Dim dvs = Await DeviceManager.Current.GetConnectedDeviceDefinitionsAsync(dfnt)
    End Sub
     End Class

`

this above code could not compile because KasperSky Free version blocked 

![image](https://user-images.githubusercontent.com/13380400/58030148-abf8b180-7b3b-11e9-8c11-194a60e64067.png)

**Comment by MelbourneDeveloper** [comment]
> Can i get all connected HID devices with it's VID and PID ?

@pc8181

First, register the Hid factory. On Windows:

```cs
WindowsUsbDeviceFactory.Register(null);
```
Then, call:
```cs
var devices = await DeviceManager.Current.GetConnectedDeviceDefinitionsAsync(null);
```
Please run this Windows sample:
https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Usb.Net.WindowsSample

You will see Hid devices like this:
![image](https://user-images.githubusercontent.com/16697547/58049415-26532100-7b90-11e9-94c3-09f6e8fe5ac7.png)

It looks like you have malware on your computer. You will need to fix your computer.

**Comment by MelbourneDeveloper** [comment]
@pc8181 your VB sample looks correct to me. You just need to fix your malware problem.

**Comment by pc8181** [comment]
thanks for your detailed reply sir sure i will try to scan and fix my computer

Thanks Sir :)

**Comment by heartacker** [comment]
@MelbourneDeveloper  i have register and program   All the way round in "await"
```
            var devices = await DeviceManager.Current.GetConnectedDeviceDefinitionsAsync(null);
```  
i am sure my hid devices are connected       
```
            WindowsHidDeviceFactory.Register(logger, tracer);
            WindowsUsbDeviceFactory.Register(logger, tracer);
            //WindowsSerialPortDeviceFactory.Register(Logger, Tracer);
            //deviceListener = new DeviceListener(df, 3000) { Logger = new DebugLogger() };
            //deviceListener.DeviceInitialized += DeviceListener_DeviceInitialized;
#if false

            //Define the types of devices to search for.
            //var df = new List<FilterDeviceDefinition>
            //{
            //       new FilterDeviceDefinition()
            //    {
            //        DeviceType = DeviceType.Hid,
            //        VendorId = 0x0d28,
            //        ProductId =0x2024
            //    }
            //};
            //var task = await DeviceManager.Current.GetConnectedDeviceDefinitionsAsync(
            //                       new FilterDeviceDefinition()
            //                       {
            //                           DeviceType = DeviceType.Hid,
            //                           VendorId = 0x0d28,
            //                           ProductId = 0x2024
            //                       });  
#endif




            var devices = await DeviceManager.Current.GetConnectedDeviceDefinitionsAsync(null);
            Console.WriteLine("Currently connected devices: ");

            foreach (var device in devices)
            {
                Console.WriteLine(device.DeviceId);
            }
```
what is wrong, help me please
thx

**Comment by MelbourneDeveloper** [comment]
@heartacker please the log output

**Comment by heartacker** [comment]
@MelbourneDeveloper I create a DLL to enumerate USB devices，and  i usd a console exe to invoke the DLL,then DLL work well. but i usd  a netcore 3.0 WPF to invoke the DLL ,the DLL does not work. :confounded:
I can deal with it,how  can  I do,thanks

**Comment by MelbourneDeveloper** [comment]
@heartacker I need to see the log output. Please post it.

**Comment by MelbourneDeveloper** [comment]
@heartacker please read:


https://github.com/MelbourneDeveloper/Device.Net/wiki/Debugging,-Logging,-and-Tracing
