### ISSUE TITLE
How use Device.Net for real time monitoring data from Hid device?

### ISSUE THREAD

**Issue by UporotayaPanda** [MelbourneDeveloper/Device.Net#61]
How I can use library for real time monitoring data from HID device?

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda connec to the device using the sample code, and then call [ReadAsync](https://github.com/MelbourneDeveloper/Device.Net/blob/3a7324746e01a0e252d2a4d1b630ed4b623f3903/src/Device.Net/IDevice.cs#L16) in a loop.

**Comment by UporotayaPanda** [comment]
@MelbourneDeveloper , what about device listener? 
I'm trying to use it
Maybe you have an example of how to implement real-time data reading?

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda 
One step at a time. Connect to a device first and make sure you can do that. Then call ReadAsync in a loop. Please post your code so I can see what you've done. There are plenty of examples for you to look at.

**Comment by UporotayaPanda** [comment]
@MelbourneDeveloper 
It's info about my mouse device.

![image](https://user-images.githubusercontent.com/25286197/58995849-7cfe6300-87fe-11e9-84a2-382012dfdc8a.png)

```
        private static async Task Read()
        {
            var definitions = new List<FilterDeviceDefinition>
            {
                new FilterDeviceDefinition
                {
                    DeviceType = DeviceType.Hid, 
                    VendorId = 0x046D, 
                    ProductId = 0xC31C
                },
                new FilterDeviceDefinition
                {
                    DeviceType = DeviceType.Hid, 
                    VendorId = 0x09DA, 
                    ProductId = 0x1985
                }
            };

            var devices = await DeviceManager.Current.GetDevicesAsync(definitions);

            if (devices.Any())
            {
                //read   
            }
        }
```

I try get my mouse and keyboard devices. But I always have null...

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda, I'm not sure that the mouse will show up. Mice are usually not custom USB devices. They are usually handled by the OS at the kernel level. 

Please see this sample and debug it. It will list all devices that can be connected to

https://github.com/MelbourneDeveloper/Device.Net/blob/3a7324746e01a0e252d2a4d1b630ed4b623f3903/src/Usb.Net.WindowsSample/Program.cs#L105

**Comment by UporotayaPanda** [comment]
@MelbourneDeveloper  It work. Thanks.
Is it possible to track the flow of data without using a loop?
Using event?

**Comment by MelbourneDeveloper** [comment]
@UporotayaPanda excellent! Unfortunately not with the existing libraries. But, if you want to look at the low level code, there would be a way to do it.
