### ISSUE TITLE
Typo on documentation

### ISSUE THREAD

**Issue by NikolayUvarov** [MelbourneDeveloper/Device.Net#68]
In wiki code example:

public async Task InitializeTrezorAsync()
        {
            //Get the first available device and connect to it
            var devices = await DeviceManager.Current.GetDevices(_DeviceDefinitions);
            TrezorDevice = devices.FirstOrDefault();
            await TrezorDevice.InitializeAsync();
        }

Function GetDevices is inimplemented. There is function GetDevicesAsync

**Comment by MelbourneDeveloper** [comment]
@NikolayUvarov thanks for pointing that out. Which page is that on?

**Comment by NikolayUvarov** [comment]
Sorry, my fault. Here it is:
https://github.com/MelbourneDeveloper/Device.Net/wiki/Device-Listener

**Comment by MelbourneDeveloper** [comment]
@NikolayUvarov I've fixed this up in a a few places. Thanks a lot.
